language: rust
cache: cargo
rust:
    - stable
    - beta
    - nightly
os:
    - linux
    - osx
before_script: (cargo install rustfmt || true)
script:
    - |
      export PATH=$PATH:~/.cargo/bin &&
      cargo build --verbose &&
      cargo test --verbose &&
      cargo doc --no-deps &&
      cargo fmt

matrix:
    allow_failures:
        - rust: nightly
