verbose = true
fn_single_line = true
fn_args_density = "Compressed"
fn_arg_indent = "Tabbed"
struct_trailing_comma = "Always"
normalize_comments = false
match_block_trailing_comma = true
match_wildcard_trailing_comma = true
use_try_shorthand = true
write_mode = "Diff"
max_width = 120
ideal_width = 100
