verbose = true
fn_args_density = "Compressed"
fn_arg_indent = "Tabbed"
struct_trailing_comma = "Always"
match_block_trailing_comma = true
match_wildcard_trailing_comma = true
use_try_shorthand = true
write_mode = "Diff"
max_width = 200
ideal_width = 100
fn_call_width = 85
